site_name: 2020_5AI_Team6

nav:
    - 'Project charter': 'project_charter_doc_1.md'
    - 'Software Requirements Specification Plan': 'software_requirements_specification_doc3.md'
    - 'Software project management plan': 'software_project_management_plan.md'
    
    
theme:
    name: readthedocs

